---
language: node_js

sudo: false

cache:
  directories:
    - node_modules
    - travis-phantomjs

env:
  matrix:
    - EMBER_CHANNEL=default
    - EMBER_CHANNEL=ember-release
    - EMBER_CHANNEL=ember-beta
    - EMBER_CHANNEL=ember-canary

matrix:
  allow_failures:
    - env: EMBER_CHANNEL=ember-release
    - env: EMBER_CHANNEL=ember-beta
    - env: EMBER_CHANNEL=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - mkdir -p travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - node -v
  - phantomjs -v
  - npm test

after_success:
  - ./scripts/travis/after-success.sh

notifications:
  slack:
    secure: fQL4QI4wBqU6Vjh2qmyzDMT+WV4o0QBxljGEC3hGsPONR9RVfrxCQ8HioRmN6bUMyV/9MP9d6lnOqAUMulfc14QN6Yck8SgxUlusv7cGmeOuhUeTRsd9KJyxtmYP/fwPd7V/m2JstLkMDg3LGtU0EcnIEKklnRTEe7YSP9+4KoQ=
